name = "coop"
description = "Coop is a cross-platform Nostr client designed for secure communication focus on simplicity and customizability."
product-name = "Coop"
identifier = "su.reya.coop"
version = "0.1.2"
resources = ["assets/*/*", "Cargo.toml", "./LICENSE", "./README.md"]
icons = [
  "assets/brand/32x32.png",
  "assets/brand/128x128.png",
  "assets/brand/128x128@2x.png",
  "assets/brand/icon.icns",
  "assets/brand/icon.ico",
]
before-packaging-command = "cargo build --release"
out-dir = "./target/release"
binaries = [
	{ path = "coop", main = true },
]
