[package]
name = "ui"
version = "0.0.0"
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
smol.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
anyhow.workspace = true
itertools.workspace = true
chrono.workspace = true

paste = "1"
regex = "1"
unicode-segmentation = "1.12.0"
uuid = "1.10"
once_cell = "1.19.0"
image = "0.25.1"
linkify = "0.10.0"
